### ISSUE TITLE
Podspec?

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/HTMLLabel#4]
I'd love to integrate this into my project through Cocoapods.

Let me know if you'd like me to write up a podspe to help.

Thanks!

**Comment by nicklockwood** [comment]
Yeah, if you wouldn't mind PR'ing one, I'll commit it.

**Comment by mergesort** [comment]
Done. See https://github.com/nicklockwood/HTMLLabel/pull/5.

**Comment by mergesort** [comment]
@nicklockwood Can you submit to Cocoapods so it can be found through `pod install`?

**Comment by nicklockwood** [comment]
You can link to this one directly from your Podfile.

**Comment by mergesort** [comment]
Oh duh, good point.
