### ISSUE TITLE
Centering text

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/HTMLLabel#6]
I've tried a few approaches, and tried to look into the code for HTMLLabel, but haven't been able to find a way to achieve the result that you'd expect if you wrapped HTML in a `<center>` tag.

The methods I've tried are
- Wrapping my HTML string in center tags:

```
label.text = @"<center>Some Cool Title</center>";
```
- Setting `text-align` CSS property on a span that's encapsulating my HTML:

```
label.text = @"<span style=\"text-align: center;\">Some Cool Title</span>";
```
- After setting the label's `text` property, taking the resulting attributedString and adding a paragraphStyle to it as such:

```
label.text = myHTMLString;
NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
paragraphStyle.alignment = NSTextAlignmentCenter;

NSMutableAttributedString *mutableAttributedString = [label.attributedText mutableCopy];
[mutableAttributedString addAttribute:NSParagraphStyleAttributeName value:[paragraphStyle copy] range:NSMakeRange(0, label.attributedText.string.length)];
label.attributedText = [mutableAttributedText copy];
```

I can't quite think of another way to do this, and thought for sure the last method would work. Any thoughts/suggestions?

Otherwise the library has worked quite great (big thanks!), and I haven't come across any problems when switching over to it quite a bit.

**Comment by nicklockwood** [comment]
Yeah, the reason none of those work is because centering isn't implemented :-P

HTMLLabel doesn't use attributed strings - I wrote my own layout engine that draws the text word by word.

Centering shouldn't be too hard to add though, it's just an offset applied to each line. I'll see what I can do.

**Comment by nicklockwood** [comment]
(PS, it also doesn't support inline CSS, because I wrote my own HTML parser. Styling has to be applied using the stylesheet dictionary. See the example apps for how to do it.)

**Comment by mergesort** [comment]
That's what I figured, but I also noticed that the attributedText was populated so I wasn't sure. Centering would be much appreciated! 😄

**Comment by nicklockwood** [comment]
OK, I added an HTMLTextAlignment style. See the Styles example in the text project for how to use it (you can also just set the textAlignment property of the label to align all the text).

**Comment by mergesort** [comment]
Worked like a charm, thanks. 

One little quirk was that if you set the `textAlignment` property before setting the stylesheet, the change wouldn't be reflected in the style (and label afterwards). In the `HTMLTokenizer`'s `update` method, where it checks against `textAlignment`, it was still showing as `NSTextAlignmentLeft`, despite the property change. Not sure if it's like that by design, but it seems a bit strange.

**Comment by nicklockwood** [comment]
Yeah, that's a bug. Try it now, it should be fixed.

**Comment by mergesort** [comment]
LGTM. :+1:
