### ISSUE TITLE
Text is drawing too tall when there is a link

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/HTMLLabel#7]
The HTMLLabel that I'm using isn't rendering text the same when there is a bolded element.

My HTML style bolds links, and a heavy version of Avenir, as this:

```
{
    a =     {
        font = "<UICTFont: 0x7ff37cc0b230> font-family: \"Avenir-Heavy\"; font-weight: bold; font-style: normal; font-size: 14.00pt";
        textColor = "UIDeviceRGBColorSpace 0.208235 0.24 0.289412 1";
        underline = 0;
    };
    "a:active" =     {
        textColor = "UIDeviceRGBColorSpace 0.741176 0.764706 0.780392 1";
    };
    html =     {
        font = "<UICTFont: 0x7ff37ca36620> font-family: \"Avenir-Roman\"; font-weight: normal; font-style: normal; font-size: 14.00pt";
        textAlignment = 0;
        textColor = "UIDeviceRGBColorSpace 0.208235 0.24 0.289412 1";
    };
}
```

This unhighlighted text works perfectly. `This is a review that has no highlighted elements.`

![ios simulator screen shot jan 22 2015 2 44 04 pm](https://cloud.githubusercontent.com/assets/716513/5863240/075c82c8-a246-11e4-8509-736e9773db7e.png)

This highlighted text makes the label quite a bit taller. `This is a review that has a <a href="picks://username?=@highlighted">@highlighted</a> element.`

![ios simulator screen shot jan 22 2015 2 44 16 pm](https://cloud.githubusercontent.com/assets/716513/5863258/2fc1a554-a246-11e4-9889-15f0f120f36d.png)

Any thoughts/suggestions?

**Comment by nicklockwood** [comment]
I'm not able to replicate it with the same text and styles you've given me (see screenshot). Can you provide a sample project, or any additional requirements to reproduce, such as the width of the field?

Also, what code are you using to calculate and set the label height?

![ios simulator screen shot 23 jan 2015 02 30 39](https://cloud.githubusercontent.com/assets/546885/5868882/20cad09a-a2a8-11e4-9d9c-300107914c53.png)

**Comment by mergesort** [comment]
Hm, that seems reasonable. The cell is laid out using AutoLayout, pinned to the edges of some views (in the screenshot above to the right of the left avatar element, pinned on the right against the edge of the cell with an inset, and in another scenario against the cell edges flat, and the same symptoms arise). 

The only thing I'm doing that may cause this is setting a preferredMaxLayoutWidth, because otherwise if it's 0 as is the default, it only renders one line max. I've tried setting the preferredMaxLayoutWidth in layoutSubviews or otherwise, as the width of the cell bounds, the appropriate width, etc, but it seems to have little effect in making it grow.

In case it wasn't evident (to be sure), the size of the label is definitely growing in that scenario too, and the cell only grows to match it.

Know anything I might not about preferredMaxLayoutWidth that might affect this, or maybe something else?

I will try and provide a sample project, it's a bit difficult to pull this out of the current codebase.

**Comment by mergesort** [comment]
I worked around this by doing something like this in my subclass.

```
- (CGSize)intrinsicContentSize
{
    if (self.preferredMaxLayoutWidth > 0)
    {
        return [self.text sizeForWidth:self.preferredMaxLayoutWidth withHTMLStyles:self.stylesheet];
    }
    else
    {
        return [super intrinsicContentSize];
    }
}
```

It seems like this should be the default implementation, though I'm not sure if it's solving a symptom of something specific to me.

**Comment by nicklockwood** [comment]
Yeah, as soon as you mentioned autolayout, it occurred to me that I probably hadn't implemented intrinsicContentSize (the class predates autolayout).

**Comment by mergesort** [comment]
Ah, ok, makes sense. Not a huge deal, might be good to implement that, but probably not a deal breaker. I'll close this issue, can open up another issue regarding auto layout if you choose.

**Comment by djibouti33** [comment]
@mergesort excellent tip on overriding -intrinsicContentSize for projects using autolayout. My labels in a UITableViewCell were rending oddly (some too large, some too small) and that override worked perfectly. Thanks!
